import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'com.google.devtools.ksp'
    id 'kotlin-kapt'
    id 'dagger.hilt.android.plugin'
    id 'com.google.dagger.hilt.android'
}

def getApiKey() {
    Properties properties = new Properties()
    def localPropertiesFile = project.rootProject.file("local.properties")
    if (localPropertiesFile.exists()) {
        properties.load(localPropertiesFile.newDataInputStream())
    }
    return properties.getProperty("MAPS_API_KEY", "")
}

android {
    namespace "com.sap.codelab"
    compileSdk = 36
    buildToolsVersion '36.0.0'
    defaultConfig {
        applicationId "com.sap.codelab"
        minSdkVersion 27
        versionCode 1
        versionName "1.0"
        manifestPlaceholders = [ MAPS_API_KEY:"${getApiKey()}" ]
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    sourceSets {
        main.java.srcDirs = ['src/main/java']
        test.java.srcDirs = ['src/test/java']
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    buildFeatures {
        viewBinding true
    }
}

kotlin {
    target {
        compilerOptions {
            jvmTarget = JvmTarget.JVM_21
        }
    }
}

ext {
    kotlinCoroutinesVersion = '1.10.2'
    roomVersion = '2.8.3'
    navVersion = "2.9.6"
    lifecycleVersion = '2.9.4'
    googleMapsVersion = '19.2.0'
    googleLocationVersion = '21.3.0'

}
apply plugin: "androidx.navigation.safeargs.kotlin"

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.fragment:fragment-ktx:1.8.9'
    implementation "androidx.activity:activity-ktx:1.11.0"
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'com.google.android.material:material:1.13.0'

    //Lifecycle, LiveData and ViewModel dependencies
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycleVersion"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycleVersion"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycleVersion"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.10.2"

    //Room persistence
    implementation "androidx.room:room-runtime:$roomVersion"
    implementation "androidx.room:room-ktx:$roomVersion"
    ksp "androidx.room:room-compiler:$roomVersion"

    //Coroutines
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinCoroutinesVersion"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$kotlinCoroutinesVersion"

    // Hilt
    implementation 'com.google.dagger:hilt-android:2.56'
    kapt 'com.google.dagger:hilt-android-compiler:2.56'
    kapt 'androidx.hilt:hilt-compiler:1.2.0'

    //Navigation
    implementation "androidx.navigation:navigation-fragment-ktx:$navVersion"
    implementation "androidx.navigation:navigation-ui-ktx:$navVersion"

    // Google Maps
    implementation "com.google.android.gms:play-services-maps:$googleMapsVersion"
    implementation "com.google.android.gms:play-services-location:$googleLocationVersion"

    //Tests
    testImplementation 'app.cash.turbine:turbine:1.2.1'
    testImplementation 'org.mockito.kotlin:mockito-kotlin:6.1.0'
    testImplementation 'org.mockito:mockito-inline:5.2.0'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2'
    testImplementation 'org.robolectric:robolectric:4.16'
    testImplementation 'androidx.arch.core:core-testing:2.2.0'
    testImplementation 'junit:junit:4.13.2'

}